(function(){
'use strict';
var DATA={
  DAE:{node:'OU3',role:'DAE · ROBOT',available:'528 400',camtel:'550 000 F',commission:'+18 450 F',reserved:'21 600 F',ops:'47',metricCommission:'18,4k',attention:'3',attentionLabel:'nœuds à suivre',momentum:'72 %',momentumWidth:'72%',momentumTitle:'Dynamique de mon réseau',navAction:'Piloter',heroAction:'PILOTER MON RÉSEAU',networkTitle:'Ma pyramide commerciale',networkIntro:'Mes DSM et leurs PoS, sans exposer les autres branches.',netActive:'38',netWatch:'3',netRobot:'96%',activityTitle:'Mon réseau aujourd’hui'},
  DSM:{node:'DSM7_OU3',role:'DSM · ROBOT',available:'126 700',camtel:'138 000 F',commission:'+7 820 F',reserved:'11 300 F',ops:'29',metricCommission:'7,8k',attention:'2',attentionLabel:'PoS à suivre',momentum:'81 %',momentumWidth:'81%',momentumTitle:'Dynamique de mes PoS',navAction:'Fournir',heroAction:'APPROVISIONNER MES POS',networkTitle:'Mes PoS',networkIntro:'Mon compte et mes PoS directs uniquement.',netActive:'14',netWatch:'2',netRobot:'93%',activityTitle:'Mes PoS aujourd’hui'},
  POS:{node:'POS16_DSM7_OU3',role:'POS · ROBOT',available:'37 450',camtel:'42 000 F',commission:'+2 760 F',reserved:'4 550 F',ops:'18',metricCommission:'2,7k',attention:'1',attentionLabel:'action à suivre',momentum:'64 %',momentumWidth:'64%',momentumTitle:'Dynamique de mes ventes',navAction:'Vendre',heroAction:'VENDRE MAINTENANT',networkTitle:'Mon point de vente',networkIntro:'Uniquement mon propre état, mes soldes et mon activité.',netActive:'1',netWatch:'1',netRobot:'100%',activityTitle:'Mon activité aujourd’hui'}
};
var role='DAE',screen='home';
function el(id){return document.getElementById(id);}function all(q){return document.querySelectorAll(q);}function set(id,v){if(el(id)){el(id).textContent=v;}}
function toast(t){var e=el('toast');e.textContent=t;e.className='toast show';window.clearTimeout(toast.timer);toast.timer=window.setTimeout(function(){e.className='toast';},2200);}
function modal(title,text){set('modalTitle',title);set('modalText',text);el('demoModal').className='modal open';el('demoModal').setAttribute('aria-hidden','false');}
function closeModal(){el('demoModal').className='modal';el('demoModal').setAttribute('aria-hidden','true');}
function showScreen(name){screen=name;all('.screen').forEach(function(s){s.className='screen'+(s.getAttribute('data-screen')===name?' active':'');});all('[data-nav]').forEach(function(b){b.className=(b.getAttribute('data-nav')==='action'?'nav-action':'')+(b.getAttribute('data-nav')===name?' active':'');});window.scrollTo(0,0);}
function quick(icon,label,tone,target){return '<button class="quick-button '+(tone||'')+'" data-quick="'+target+'"><span>'+icon+'</span>'+label+'</button>';}
function renderQuick(){var html='';if(role==='DAE'){html+=quick('↗','APPROVISIONNER','gold','action');html+=quick('⌁','RÉSEAU','mint','network');html+=quick('◫','SOLDES','','network');html+=quick('◉','ROBOT','violet','manage');}else if(role==='DSM'){html+=quick('↗','FOURNIR POS','gold','action');html+=quick('↓','DEMANDER DAE','','action');html+=quick('⌁','MES POS','mint','network');html+=quick('◉','ROBOT','violet','manage');}else{html+=quick('⚡','VENDRE','gold','action');html+=quick('↓','DEMANDER DSM','','action');html+=quick('◫','MON SOLDE','mint','network');html+=quick('◉','ROBOT','violet','manage');}el('quickGrid').innerHTML=html;all('[data-quick]').forEach(function(b){b.onclick=function(){showScreen(b.getAttribute('data-quick'));};});}
function event(icon,tone,title,meta,value){return '<div class="event-row"><span class="event-icon '+tone+'">'+icon+'</span><div class="event-copy"><b>'+title+'</b><span>'+meta+'</span></div><span class="event-value">'+value+'</span></div>';}
function renderActivity(){var h='';if(role==='DAE'){h+=event('✓','mint','DSM7_OU3 · Approvisionnement confirmé','Il y a 4 min · base + commission','+54 000 F');h+=event('⚡','','POS16_DSM7_OU3 · Vente Blue réussie','Il y a 6 min · CurrentBalance rapproché','+1 000 F');h+=event('!','gold','DSM12_OU3 · Solde à recertifier','Mouvement détecté après la dernière preuve','À suivre');h+=event('∞','','Réseau Robot stable','38 nœuds visibles · aucun blocage global','96 %');}else if(role==='DSM'){h+=event('✓','mint','POS16_DSM7_OU3 · Approvisionnement confirmé','Il y a 3 min · commission 8 %','+21 600 F');h+=event('⚡','','POS8_DSM7_OU3 · Vente réussie','Il y a 9 min · preuve finale reçue','+2 000 F');h+=event('!','gold','POS5_DSM7_OU3 · Solde à revoir','Preuve exacte expirée après mouvement','À suivre');h+=event('∞','','Robot DSM stable','14 PoS visibles · 1 SIM active','93 %');}else{h+=event('✓','mint','Vente Blue réussie','Il y a 1 min · client 6XX XXX XXX','+1 000 F');h+=event('◫','','Solde Camtel actualisé','Il y a 7 min · preuve exacte','42 000 F');h+=event('↗','gold','Approvisionnement reçu','Il y a 21 min · DSM7_OU3','+10 800 F');h+=event('∞','','Robot PoS actif','Aucune file bloquée','ACTIF');}el('activityTimeline').innerHTML=h;el('homeTimeline').innerHTML=h.split('</div><div class="event-row">').slice(0,3).join('</div><div class="event-row">');}
function nodeCard(code,type,balance,status,children){return '<article class="node-card"><div class="node-top"><div class="node-id"><i class="node-dot '+(status==='À suivre'?'warn':'')+'"></i><div><b>'+code+'</b><small>'+type+' · '+status+'</small></div></div><div class="node-money"><b>'+balance+'</b><small>disponible démo</small></div></div><div class="node-meta"><span class="node-chip">ROBOT '+(status==='Actif'?'ACTIF':'À VÉRIFIER')+'</span><span class="node-chip">PREUVE '+(status==='Actif'?'FRAÎCHE':'À REVOIR')+'</span></div>'+(children?'<div class="node-children">'+children+'</div>':'')+'</article>';}
function renderNetwork(){var h='';if(role==='DAE'){var c1=nodeCard('POS16_DSM7_OU3','PoS','37 450 F','Actif','')+nodeCard('POS8_DSM7_OU3','PoS','28 200 F','Actif','');var c2=nodeCard('POS5_DSM12_OU3','PoS','9 800 F','À suivre','');h+=nodeCard('DSM7_OU3','DSM','126 700 F','Actif',c1)+nodeCard('DSM12_OU3','DSM','88 350 F','À suivre',c2)+nodeCard('DSM3_OU3','DSM','74 900 F','Actif','');set('networkInsight','Les preuves fraîches des DSM/PoS doivent remonter dans la pyramide avant tout nouvel USSD inutile.');}else if(role==='DSM'){h+=nodeCard('POS16_DSM7_OU3','PoS','37 450 F','Actif','')+nodeCard('POS8_DSM7_OU3','PoS','28 200 F','Actif','')+nodeCard('POS5_DSM7_OU3','PoS','9 800 F','À suivre','')+nodeCard('POS2_DSM7_OU3','PoS','18 600 F','Actif','');set('networkInsight','Le DSM ne voit que ses PoS. Une branche sœur du même DAE reste invisible.');}else{h+=nodeCard('POS16_DSM7_OU3','Mon PoS','37 450 F','Actif','');set('networkInsight','Le PoS ne voit que lui-même : son solde, son Robot, ses ventes et ses preuves.');}el('networkTree').innerHTML=h;}
function field(label,placeholder,type){return '<div class="field"><label>'+label+'</label><input type="'+(type||'text')+'" placeholder="'+placeholder+'" disabled></div>';}
function actionCard(title,desc,fields,button,primary){return '<article class="action-card '+(primary?'primary-card':'')+'"><p class="eyebrow dark">PROTOTYPE SANS FONDS</p><h3>'+title+'</h3><p>'+desc+'</p><div class="field-grid">'+fields+'</div><button class="action-button '+(primary?'gold':'')+'" data-prototype-action="'+button+'">'+button+'</button></article>';}
function renderActions(){var h='';if(role==='DAE'){set('actionTitle','Piloter et approvisionner');set('actionIntro','Priorité à mes DSM, avec visibilité de ma pyramide.');h+=actionCard('Approvisionner un DSM','Prévisualisation base + commission avant confirmation.',field('DSM cible','Ex. DSM7')+field('Montant de base','Ex. 50 000','number'),'PRÉVISUALISER',true);h+=actionCard('Consulter une preuve réseau','Réutiliser une preuve fraîche si elle existe avant tout nouvel USSD.',field('Nœud','Ex. DSM7 ou POS16_DSM7_OU3'),'VÉRIFIER LA FRAÎCHEUR',false);}else if(role==='DSM'){set('actionTitle','Approvisionner mes PoS');set('actionIntro','Fournir mes PoS ou demander du stock à mon DAE.');h+=actionCard('Approvisionner un PoS','Prévisualisation base + commission 8 % par défaut, surcharge possible.',field('PoS cible','Ex. POS16')+field('Montant de base','Ex. 10 000','number'),'PRÉVISUALISER',true);h+=actionCard('Demander à mon DAE','Aucune réservation avant la confirmation finale.',field('Montant souhaité','Ex. 50 000','number'),'PRÉPARER LA DEMANDE',false);}else{set('actionTitle','Vendre maintenant');set('actionIntro','Parcours PoS : client, montant, vérification, confirmation.');h+=actionCard('Vente Blue client','Aucun débit n’est effectué dans cette maquette.',field('Numéro client','6XXXXXXXX','tel')+field('Montant','Ex. 1 000','number'),'PRÉVISUALISER LA VENTE',true);h+=actionCard('Demander du stock à mon DSM','Prépare une intention de demande sans aucune opération réelle.',field('Montant souhaité','Ex. 20 000','number'),'PRÉPARER LA DEMANDE',false);}el('actionCards').innerHTML=h;all('[data-prototype-action]').forEach(function(b){b.onclick=function(){modal('Action simulée',b.getAttribute('data-prototype-action')+' : interface seulement. Aucun USSD, aucune réservation et aucun débit.');};});}
function renderRole(){var d=DATA[role];set('heroNode',d.node);set('heroRole',d.role);set('availableBalance',d.available);set('camtelBalance',d.camtel);set('commissionToday',d.commission);set('reservedBalance',d.reserved);set('metricOps',d.ops);set('metricCommission',d.metricCommission);set('metricAttention',d.attention);set('metricAttentionLabel',d.attentionLabel);set('momentumTitle',d.momentumTitle);set('momentumPct',d.momentum);el('momentumBar').style.width=d.momentumWidth;set('heroPrimary',d.heroAction);set('networkTitle',d.networkTitle);set('networkIntro',d.networkIntro);set('netActive',d.netActive);set('netWatch',d.netWatch);set('netRobot',d.netRobot);set('activityTitle',d.activityTitle);set('navActionLabel',d.navAction);renderQuick();renderActivity();renderNetwork();renderActions();el('managePinGroup').style.display='block';}
all('[data-nav]').forEach(function(b){b.onclick=function(){showScreen(b.getAttribute('data-nav'));};});all('[data-open-screen]').forEach(function(b){b.onclick=function(){showScreen(b.getAttribute('data-open-screen'));};});all('[data-demo-action]').forEach(function(b){b.onclick=function(){modal('Centre Gérer — prototype',b.getAttribute('data-demo-action')+' : démonstration uniquement. Le vrai moteur v2.6.8 n’est pas connecté à cette branche.');};});el('heroPrimary').onclick=function(){showScreen('action');};el('roleSelect').onchange=function(){role=this.value;renderRole();toast('Aperçu '+role+' chargé — données de démonstration.');};el('modalClose').onclick=closeModal;el('demoModal').onclick=function(e){if(e.target===el('demoModal')){closeModal();}};renderRole();showScreen('home');
}());
